# DB 생성
DROP DATABASE IF EXISTS LSS;
CREATE DATABASE LSS;

# DB 선택
USE LSS;

# 게시물 테이블 생성
CREATE TABLE article (
	id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	regDate DATETIME NOT NULL,
	updateDate DATETIME NOT NULL,
	title CHAR(100) NOT NULL,
	memberId INT NOT NULL,
	`body` TEXT NOT NULL,
	hit INT(10) UNSIGNED NOT NULL
);

# 회원 테이블 생성
CREATE TABLE `member` (
	id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	regDate DATETIME NOT NULL,
	updateDate DATETIME NOT NULL,
	loginId CHAR(20) NOT NULL,
	loginPw CHAR(100) NOT NULL,
	`name` CHAR(200) NOT NULL,
	nickname CHAR(20) NOT NULL,
	birth CHAR(20) NOT NULL
);

SELECT * FROM article;
SELECT * FROM `member`;